### ISSUE TITLE
Example of  n-queens.

### ISSUE THREAD

**Issue by Average-user** [Anniepoo/prolog-examples#5]
Would you like an example of the n-queens problem?

see [https://en.wikipedia.org/wiki/Eight_queens_puzzle](https://en.wikipedia.org/wiki/Eight_queens_puzzle) if you don't already know it, wich is very unlikely, since is a classic problem in programming.

**Comment by Anniepoo** [comment]
Hey, sorry, missed this. Yes, love to have an n queens problem

**Comment by Anniepoo** [comment]
Thanks!  PR accepted, closing
